[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 0
evm_version = "cancun"

# Add an explicit return with value to all non-reverting code paths or name the variable
ignored_error_codes = [3860, 5574, 6321]

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "params_first"
sort_imports = true
line_length = 120
tab_width = 4
int_types = "short"
quote_style = "single"
number_underscore = "preserve"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
